# Generated by Django 4.2.5 on 2023-09-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("tipo", models.CharField(max_length=50)),
                ("numPokedex", models.IntegerField()),
                ("imageUrl", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "pokemon1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon1",
                        to="Pokemon.pokemon",
                    ),
                ),
                (
                    "pokemon2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon2",
                        to="Pokemon.pokemon",
                    ),
                ),
                (
                    "pokemon3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon3",
                        to="Pokemon.pokemon",
                    ),
                ),
                (
                    "pokemon4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon4",
                        to="Pokemon.pokemon",
                    ),
                ),
                (
                    "pokemon5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon5",
                        to="Pokemon.pokemon",
                    ),
                ),
                (
                    "pokemon6",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador_pokemon6",
                        to="Pokemon.pokemon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enfrentamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_combate", models.DateField()),
                ("finalizado", models.BooleanField()),
                (
                    "entrenador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfrentamientos_entrenador1",
                        to="Pokemon.entrenador",
                    ),
                ),
                (
                    "entrenador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfrentamientos_entrenador2",
                        to="Pokemon.entrenador",
                    ),
                ),
                (
                    "ganador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfrentamientos_ganados",
                        to="Pokemon.entrenador",
                    ),
                ),
            ],
        ),
    ]
